Update osgbindlesstext.cpp
After apply all the texture object and make it resident in GPU,we can unref all the images of each texture.To achieve that,I use a vector storing   
osg::Image* instead of osg::ref_prt<osg::Image>,and unref to release all osg::image's memory.After doing this, memory costing downs to 70MB from 315MB IN MY machine.And another modifying is adding "//" before #extension in vert-shader,to avoid error C7621